{{- if .Values.pgbouncer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timescale.pgbouncer.fullname" . }}-secret
  labels:
    {{- include "timescale.pgbouncer.labels" . | nindent 4 }}
type: Opaque
stringData:
  userlist.txt: |
    "{{ .Values.postgres.user }}" "{{ .Values.postgres.password }}"
{{- if .Values.pgbouncer.additionalUsers }}
{{- range .Values.pgbouncer.additionalUsers }}
    "{{ .username }}" "{{ .password }}"
{{- end }}
{{- end }}
{{- end }}
