apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timescale.secretName" . }}
  labels:
    {{- include "timescale.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.pgbouncer.enabled }}
  PGHOST: {{ printf "%s.%s.svc.cluster.local" (include "timescale.pgbouncer.fullname" .) .Release.Namespace | b64enc | quote }}
  {{- else }}
  PGHOST: {{ printf "%s.%s.svc.cluster.local" (include "timescale.fullname" .) .Release.Namespace | b64enc | quote }}
  {{- end }}
  PGPORT: {{ .Values.postgres.port | toString | b64enc | quote }}
  PGDATABASE: {{ .Values.postgres.database | b64enc | quote }}
  PGUSER: {{ .Values.postgres.user | b64enc | quote }}
  PGPASSWORD: {{ .Values.postgres.password | b64enc | quote }}
